server:
  port: 7777
spring:
  application:
    name: static-sidecar
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

sidecar:
  port: 7776                                     # 本地的 nginx 服务端口
  health-uri: http://localhost:7776/health.json  # 健康检查